Encoding:
  Enabled: true

LineLength:
  Enabled: true
  Max: 80

AllCops:
  Includes:
    - Rakefile
    - config.ru
  Excludes:
    - db/**
    - config/**
    - script/**
    - lib/**
    - public/**
    - doc/**
